name: My base action

on:
  workflow_call:
    inputs:
      my-input:
        type: string
        required: true
        description: 'My input description'


jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
    - name: My step
      run: echo "Hello, ${{ inputs.my-input }}"
