on:
  workflow_dispatch:

jobs:
  job-bytag:
    runs-on: ubuntu-latest
    steps:
      - name: My step
        uses: Battleman/greedy-action@2
        with:
          my-input: "By tab"
  job-byhash:
    runs-on: ubuntu-latest
    steps:
      - name: My step
        uses: Battleman/greedy-action@2b6be65d39c55059d4c92108b1881d76bfe25244
        with:
          my-input: "world"
  job-bybranch:
    runs-on: ubuntu-latest
    steps:
      - name: My step
        uses: Battleman/greedy-action@base-action
        with:
          my-input: "world"
