on:
  workflow_dispatch:

jobs:
  job-bytag:
    uses: Battleman/greedy-action/.github/workflows/baseaction.yml@3
    with:
      my-input: "By tag"
  job-byhash:
    uses: Battleman/greedy-action/.github/workflows/baseaction.yml@31525031d9873acb2fa8152e8c906a519ee9f939
    with:
      my-input: "By hash"
  job-bybranch:
    uses: Battleman/greedy-action/.github/workflows/baseaction.yml@base-action
    with:
      my-input: "By branch"
